general {
    hide_cursor = true
}

background {
    color = rgb(000000)
}

input-field {
    size = 300, 50
    outline_thickness = 0
    dots_center = true
    fade_on_empty = false
    font_color = rgb(cdd6f4)
    inner_color = rgb(000000)
    check_color = rgb(a6e3a1)
    fail_color = rgb(f38ba8)
    placeholder_text = Password
}
